name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - 'app/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
